"""Owner-approved evolution of the agent's own character.

## Why this exists

The agent already maintains a precise, continuously-refreshed model of how it
WORKS: 202 files under knowledge/self/modules, one per source module,
regenerated by FIRE_SELF_STUDY within minutes of any code change.

It had nothing equivalent for who it IS. Measured 2026-08-10:

    self/modules/tools__agent_browser.md   updated Aug 10 11:24  (automatic)
    identity/soul.md                       updated Jul  7        (by a human)
    identity/identity.md                   updated Jun 16        (by a human)

soul.md reaches every single turn — IDENTITY.preamble() builds a `# SOUL`
block at unified_agent.py:542 and :2548 — so it is not dead text; it is the
character the agent acts from. But it was frozen. Everything the agent
learned about being useful to this particular person, over a month of daily
work, went nowhere. FIRE_SELF_REFLECTION sounds like the counterpart and is
not: it extracts failure patterns via META_LEARNER and never touches
identity.

So: the agent may now revise its own character — and every revision waits for
the owner. That is the owner's explicit choice, and it is the right one. A
character an agent rewrites unilaterally is no longer the character its
person gave it; a character that can never change is a photograph of who it
was in June.

## Shape

Deliberately the same shape as `self_modifier`: propose -> owner approves ->
apply, with every applied revision snapshotting the previous text so any
version can be restored. The agent writes the proposal; the owner holds the
pen.
"""
from __future__ import annotations

import json
import logging
import time
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger(__name__)

# A revision may not rewrite the character wholesale. The agent proposes an
# EDIT — an old excerpt and its replacement — so the owner reviews a diff, not
# a new document. Wholesale replacement is how "evolution" becomes
# "substitution".
MAX_EXCERPT_CHARS = 4000

_VALID_STATUS = ("pending", "approved", "applied", "rejected", "failed")


@dataclass
class SoulRevision:
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:10])
    target: str = "soul"                 # "soul" | "identity"
    rationale: str = ""                  # WHY — shown to the owner first
    old_excerpt: str = ""                # must appear verbatim, exactly once
    new_excerpt: str = ""
    evidence: str = ""                   # what in real turns prompted this
    status: str = "pending"
    created_at: float = field(default_factory=time.time)
    decided_at: float = 0.0
    note: str = ""
    snapshot: str = ""                   # _history file written on apply

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "SoulRevision":
        known = {k: v for k, v in (d or {}).items()
                 if k in cls.__dataclass_fields__}
        return cls(**known)

    def has_diff(self) -> bool:
        return bool((self.old_excerpt or "").strip()
                    or (self.new_excerpt or "").strip())


class SoulEvolution:
    def __init__(self, path: Path | None = None) -> None:
        self._path = path
        self._revisions: list[SoulRevision] = []
        self._loaded = False

    # ---------- storage ----------

    def _store_path(self) -> Path:
        if self._path is not None:
            return self._path
        from .config import CONFIG
        return (Path(CONFIG.knowledge["base_dir"]) / "identity"
                / "soul_revisions.json")

    def _load(self) -> None:
        if self._loaded:
            return
        self._loaded = True
        p = self._store_path()
        try:
            raw = json.loads(p.read_text(encoding="utf-8"))
            self._revisions = [SoulRevision.from_dict(d) for d in raw]
        except Exception:
            self._revisions = []

    def _save(self) -> None:
        p = self._store_path()
        try:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(
                json.dumps([r.to_dict() for r in self._revisions],
                           ensure_ascii=False, indent=1),
                encoding="utf-8")
        except OSError as e:
            log.warning("soul_evolution: could not persist revisions: %s", e)

    # ---------- the target files ----------

    def _target_path(self, target: str) -> Path:
        from .identity import IDENTITY
        return (IDENTITY.soul_path if target == "soul"
                else IDENTITY.identity_path)

    def _history_dir(self) -> Path:
        from .identity import IDENTITY
        d = IDENTITY.history_dir
        d.mkdir(parents=True, exist_ok=True)
        return d

    # ---------- the loop ----------

    def propose(self, *, target: str, rationale: str, old_excerpt: str,
                new_excerpt: str, evidence: str = "") -> "SoulRevision | None":
        """Register a proposed character edit. Returns None when the edit
        cannot be applied later, so a revision never sits pending for the
        owner's attention on something that could never land."""
        self._load()
        if target not in ("soul", "identity"):
            return None
        old = (old_excerpt or "").strip()
        new = (new_excerpt or "").strip()
        if not (old or new):
            return None
        if len(old) > MAX_EXCERPT_CHARS or len(new) > MAX_EXCERPT_CHARS:
            return None
        if not (rationale or "").strip():
            # An unexplained character change is not reviewable, and the
            # owner is the reviewer.
            return None
        if old:
            try:
                body = self._target_path(target).read_text(encoding="utf-8")
            except OSError:
                return None
            if body.count(old) != 1:
                # Zero: it does not match. More than one: ambiguous, and a
                # silent first-hit replace is how an edit lands in the wrong
                # paragraph — the same rule self_modifier applies to code.
                return None
        rev = SoulRevision(target=target, rationale=rationale.strip(),
                           old_excerpt=old, new_excerpt=new,
                           evidence=(evidence or "").strip())
        self._revisions.append(rev)
        self._save()
        _fire_revision_proposed(rev)
        return rev

    def list(self, status: str | None = None) -> list[SoulRevision]:
        self._load()
        if status:
            return [r for r in self._revisions if r.status == status]
        return list(self._revisions)

    def get(self, rev_id: str) -> "SoulRevision | None":
        self._load()
        return next((r for r in self._revisions if r.id == rev_id), None)

    def _owner_gate(self, speaker: str | None) -> dict | None:
        """None when the caller may change the character, else a refusal.

        `speaker` is explicit because a Telegram inline-button click runs
        outside the turn that set the speaker ContextVar — gating purely on
        current_speaker() would refuse the owner's own tap."""
        from .roles import current_speaker, is_owner
        sp = speaker if speaker is not None else current_speaker()
        if not is_owner(sp):
            return {"ok": False,
                    "message": f"character changes are owner-only; "
                               f"speaker {sp!r} is not owner"}
        return None

    def decide(self, rev_id: str, *, approve: bool, note: str = "",
               speaker: str | None = None) -> dict:
        """Owner-only. Approving does NOT apply — apply() is the separate,
        auditable step, exactly as with code proposals."""
        refusal = self._owner_gate(speaker)
        if refusal:
            return refusal
        rev = self.get(rev_id)
        if rev is None:
            return {"ok": False, "message": "revision not found"}
        rev.status = "approved" if approve else "rejected"
        rev.decided_at = time.time()
        rev.note = note or ""
        self._save()
        return {"ok": True, "status": rev.status}

    def apply(self, rev_id: str, *, speaker: str | None = None) -> dict:
        """Write an approved revision, snapshotting the previous text first."""
        refusal = self._owner_gate(speaker)
        if refusal:
            return refusal
        rev = self.get(rev_id)
        if rev is None:
            return {"ok": False, "message": "revision not found"}
        if rev.status != "approved":
            return {"ok": False,
                    "message": f"revision is {rev.status}, not approved"}
        if not rev.has_diff():
            return {"ok": False, "message": "revision has no diff"}

        path = self._target_path(rev.target)
        try:
            body = path.read_text(encoding="utf-8")
        except OSError as e:
            rev.status = "failed"
            self._save()
            return {"ok": False, "message": f"cannot read {rev.target}: {e}"}

        if rev.old_excerpt:
            if body.count(rev.old_excerpt) != 1:
                # The character moved under the proposal. Refuse rather than
                # guess — this is the owner's voice, not a config value.
                rev.status = "failed"
                rev.note += " | excerpt no longer matches exactly once"
                self._save()
                return {"ok": False, "message": (
                    f"the {rev.target} text changed since this was proposed; "
                    "re-propose against the current text")}
            new_body = body.replace(rev.old_excerpt, rev.new_excerpt, 1)
        else:
            new_body = body.rstrip("\n") + "\n\n" + rev.new_excerpt + "\n"

        # Snapshot BEFORE writing — this is what makes rollback real.
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        snap = self._history_dir() / f"{rev.target}_{ts}_{rev.id}.md"
        try:
            snap.write_text(body, encoding="utf-8")
        except OSError as e:
            rev.status = "failed"
            self._save()
            return {"ok": False,
                    "message": f"refusing to write without a snapshot: {e}"}

        try:
            path.write_text(new_body, encoding="utf-8")
        except OSError as e:
            rev.status = "failed"
            self._save()
            return {"ok": False, "message": f"write failed: {e}"}

        rev.status = "applied"
        rev.snapshot = str(snap)
        rev.decided_at = time.time()
        self._save()
        return {"ok": True, "message": f"{rev.target} updated",
                "snapshot": str(snap)}

    # ---------- rollback ----------

    def versions(self, target: str = "soul") -> list[dict]:
        """Every snapshot for a target, newest first."""
        out = []
        try:
            for p in sorted(self._history_dir().glob(f"{target}_*.md"),
                            reverse=True):
                try:
                    st = p.stat()
                except OSError:
                    continue
                out.append({"file": str(p), "name": p.name,
                            "bytes": st.st_size, "mtime": st.st_mtime})
        except Exception:
            return []
        return out

    def rollback(self, snapshot_name: str, target: str = "soul",
                 *, speaker: str | None = None) -> dict:
        """Restore a previous version. The CURRENT text is snapshotted first,
        so rolling back is itself undoable — a one-way rollback is how you
        lose the thing you were trying to protect."""
        refusal = self._owner_gate(speaker)
        if refusal:
            return refusal
        snap = self._history_dir() / Path(snapshot_name).name
        if not snap.is_file():
            return {"ok": False, "message": f"no such version: {snapshot_name}"}
        path = self._target_path(target)
        try:
            current = path.read_text(encoding="utf-8")
            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            (self._history_dir() / f"{target}_{ts}_prerollback.md").write_text(
                current, encoding="utf-8")
            path.write_text(snap.read_text(encoding="utf-8"), encoding="utf-8")
        except OSError as e:
            return {"ok": False, "message": f"rollback failed: {e}"}
        return {"ok": True, "message": f"{target} restored from {snap.name}"}


SOUL_EVOLUTION = SoulEvolution()


# ─── "a revision is waiting for you" notification ───────────────────

_ON_REVISION_PROPOSED: list = []


def register_on_revision_proposed(fn) -> None:
    """Add a callback fired when the agent proposes a character change.
    The Telegram bridge uses it to DM the owner with approval buttons.
    Idempotent."""
    if fn not in _ON_REVISION_PROPOSED:
        _ON_REVISION_PROPOSED.append(fn)


def _fire_revision_proposed(rev: SoulRevision) -> None:
    for fn in list(_ON_REVISION_PROPOSED):
        try:
            fn(rev)
        except Exception as e:
            log.warning("soul revision callback %s failed: %s", fn, e)


def render_revision_for_telegram(rev: SoulRevision) -> str:
    """The diff, as the owner should see it before deciding."""
    import difflib
    from . import tg_interactive as _tg
    if rev.old_excerpt:
        body = "\n".join(difflib.unified_diff(
            rev.old_excerpt.splitlines(), rev.new_excerpt.splitlines(),
            fromfile=f"a/{rev.target}.md", tofile=f"b/{rev.target}.md",
            lineterm="")) or "[no textual difference]"
    else:
        body = "+ " + "\n+ ".join(rev.new_excerpt.splitlines())
    if len(body) > 3400:
        body = body[:3400] + "\n…[truncated]"
    return (f"📜 <b>Character diff — {_tg.escape_html(rev.target)}.md</b>\n"
            f"<pre>{_tg.escape_html(body)}</pre>")


def _register_soul_callback() -> None:
    """Inline-button bridge. callback_data shapes:
      soul:diff:<id>    show the diff
      soul:apply:<id>   approve and write it (snapshot first)
      soul:reject:<id>  drop it
    """
    from . import tg_interactive as _tg
    from . import roles as _roles_mod

    def _handler(parts, ctx):
        if len(parts) < 2:
            return _tg.CallbackResult(ok=False, toast="malformed callback")
        clicker = ctx.get("clicker_speaker_id") or ""
        if not _roles_mod.is_owner(clicker):
            return _tg.CallbackResult(
                ok=False, clear_keyboard=False,
                toast="only the owner can change the agent's character")
        action, rid = parts[0], parts[1]
        rev = SOUL_EVOLUTION.get(rid)
        if rev is None:
            return _tg.CallbackResult(ok=False, toast="revision not found",
                                      clear_keyboard=False)
        if action == "diff":
            return _tg.CallbackResult(
                ok=True, toast="diff sent", clear_keyboard=False,
                followup_text=render_revision_for_telegram(rev))
        if action == "apply":
            SOUL_EVOLUTION.decide(rid, approve=True, speaker=clicker,
                                  note=f"approved via Telegram by {clicker}")
            res = SOUL_EVOLUTION.apply(rid, speaker=clicker)
            if not res.get("ok"):
                return _tg.CallbackResult(
                    ok=False, toast=(res.get("message") or "apply failed")[:190],
                    edited_text=("❌ <b>Not applied</b>\n<i>"
                                 f"{_tg.escape_html(res.get('message') or '')}</i>"))
            return _tg.CallbackResult(
                ok=True, toast="character updated",
                edited_text=(f"✅ <b>{_tg.escape_html(rev.target)}.md updated.</b>\n"
                             f"Previous version saved — say «откати душу» to "
                             f"restore it."))
        if action == "reject":
            SOUL_EVOLUTION.decide(rid, approve=False, speaker=clicker,
                                  note=f"rejected via Telegram by {clicker}")
            return _tg.CallbackResult(
                ok=True, toast="rejected",
                edited_text=(f"❌ <b>Rejected</b> — character unchanged "
                             f"(<code>{_tg.escape_html(rid)}</code>)."))
        return _tg.CallbackResult(ok=False, toast=f"unknown action {action!r}")

    _tg.register_callback_handler("soul", _handler)


_register_soul_callback()
