"""Engine update + rollback ledger.

The engine repo (where backend/, frontend/, deploy/ live) is just a
git checkout. `hrant update` keeps it in sync with `origin/master`
and runs the supporting dep-install / build steps. `hrant rollback`
uses the ledger this module writes to revert to a previous SHA.

Update flow:
  1. Refuse if working tree is dirty (user has uncommitted tracked
     changes — we don't want to lose them).
  2. `git fetch origin` to learn about new commits.
  3. Record current SHA + timestamp into the history ledger.
  4. `git pull --ff-only origin <branch>`. Reject on non-fast-forward
     (someone divergent-pushed; user must resolve manually).
  5. `pip install -e .` so any pyproject.toml dep changes apply.
  6. Optional `cd frontend && npm install && npm run build` (skipped
     with --skip-frontend or when --no-build is set).
  7. Print a one-line "restart hrant" reminder.

Failures at steps 4-6 are surfaced verbatim to the user; we do NOT
attempt auto-rollback because the failure may be unrelated to the
update (network, npm registry down, …) and the rollback path can
make things worse. The history entry has already been written
before the pull, so `hrant rollback` is available if needed.

Ledger format (`paths.history_path()`):
  {
    "entries": [
      {
        "sha": "abc1234...",
        "timestamp": "2026-05-13T15:42:08Z",
        "branch": "master",
        "result": "success" | "failed_at_pull" | ...
      },
      ...
    ]
  }

Newest entry last. Bounded to MAX_HISTORY_ENTRIES so the file
doesn't grow forever; older entries dropped from the front when the
cap is exceeded.
"""
from __future__ import annotations

import json
import logging
import subprocess
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from . import paths

log = logging.getLogger(__name__)


MAX_HISTORY_ENTRIES = 50


@dataclass
class HistoryEntry:
    sha: str
    timestamp: str
    branch: str
    result: str  # "success" | "failed_at_<step>"
    note: str = ""


@dataclass
class UpdateResult:
    ok: bool
    old_sha: str
    new_sha: Optional[str]
    branch: str
    pulled_commits: int
    pip_ran: bool
    frontend_built: bool
    error: Optional[str] = None
    messages: Optional[list[str]] = None
    # `hrant update` now archives every active self-mod into
    # data_dir/self_mods/history/<ts>/ instead of trying to re-apply
    # them. The engine comes out at exactly origin/master; the user
    # re-applies what they want from Settings → Self-Modifications →
    # History. These fields surface the archive event:
    self_mods_archived: int = 0
    self_mods_archive_id: Optional[str] = None
    # `cancelled=True` when the user said "no" at the pre-update prompt.
    # The result is still ok=False but the error indicates user intent
    # rather than a system failure.
    cancelled: bool = False


# --- git helpers --------------------------------------------------------


def _git(*args: str, cwd: Optional[Path] = None, check: bool = True) -> subprocess.CompletedProcess:
    """Run a git command in the engine repo. Returns the completed
    process so callers can inspect stdout/stderr. `check=True` raises
    on non-zero exit (the wrapper catches it for nicer messages)."""
    return subprocess.run(
        ["git", *args],
        cwd=str(cwd or paths.repo_root()),
        capture_output=True,
        text=True,
        check=check,
    )


def current_sha() -> str:
    """`git rev-parse HEAD` — the SHA the running engine is at."""
    try:
        r = _git("rev-parse", "HEAD")
        return r.stdout.strip()
    except subprocess.CalledProcessError:
        return ""


def current_branch() -> str:
    try:
        r = _git("rev-parse", "--abbrev-ref", "HEAD")
        return r.stdout.strip()
    except subprocess.CalledProcessError:
        return ""


def is_dirty() -> bool:
    """True if the working tree has uncommitted tracked changes.
    Untracked files (e.g. gitignored knowledge/) do NOT count."""
    try:
        r = _git("diff-index", "--quiet", "HEAD", "--", check=False)
        return r.returncode != 0
    except FileNotFoundError:
        # git not installed — can't tell, treat as dirty to refuse.
        return True


# Files known to be regenerated by `hrant update`'s own steps —
# `npm install` rewrites `frontend/package-lock.json` (libc / os
# platform fields), `pip install -e .` can rewrite metadata. Local
# edits to these files are noise, not work, so they shouldn't block
# the update. Everything else still blocks like before.
_AUTO_REGENERATED_FILES: set[str] = {
    "frontend/package-lock.json",
}


def dirty_tracked_files() -> list[str]:
    """Paths (POSIX-style, repo-relative) with uncommitted tracked
    changes. Empty list when the tree is clean.

    Used by the auto-stash logic in `update_to_latest` to tell
    "noise the next step will overwrite anyway" from "actual WIP the
    user would lose if we stashed and dropped"."""
    try:
        r = _git("diff-index", "--name-only", "HEAD", "--", check=False)
    except FileNotFoundError:
        return []
    if r.returncode != 0 or not r.stdout.strip():
        # Non-zero with no stdout = git error; treat as no info.
        return [] if not r.stdout.strip() else []
    return [ln.strip() for ln in r.stdout.splitlines() if ln.strip()]


def only_auto_regenerated_files_dirty() -> bool:
    """True iff every dirty tracked file is in the auto-regenerated
    whitelist. False on a clean tree (nothing to auto-stash) and on
    any tree with at least one real WIP edit (which must keep
    blocking the update — auto-stashing it would feel like data
    loss)."""
    files = dirty_tracked_files()
    if not files:
        return False
    return all(f in _AUTO_REGENERATED_FILES for f in files)


def stash_auto_regenerated(message: str) -> bool:
    """Stash only the auto-regenerated files. Returns True if a stash
    was created. The stash gets a distinctive message so the user can
    find it in `git stash list` if something goes wrong.

    We stash specific paths instead of the whole tree so the user's
    other untracked work (knowledge/, workspace/, dev/) is never
    touched."""
    paths_list = [f for f in dirty_tracked_files() if f in _AUTO_REGENERATED_FILES]
    if not paths_list:
        return False
    try:
        r = _git("stash", "push", "-m", message, "--", *paths_list, check=False)
        return r.returncode == 0
    except FileNotFoundError:
        return False


def self_mod_owned_files() -> set[str]:
    """Files that are dirty because a self-modification is applied there.

    Being modified is what "applied" means for a self-mod, so these are
    the expected state of the tree, not work in progress. They are safe
    to set aside for the pull: the patch files under
    `~/.hrant/data/self_mods/` hold the content, and
    `self_mods.archive_all_active()` re-applies afterwards whichever ones
    still fit.
    """
    try:
        from . import self_mods
        return self_mods.active_patch_targets()
    except Exception as exc:
        log.warning("could not read self-mod targets (%s); "
                    "treating every dirty file as work in progress", exc)
        return set()


def only_expected_files_dirty() -> bool:
    """True iff every dirty tracked file is one the update may set aside.

    Two kinds qualify: lockfiles the next install step rewrites anyway,
    and files an active self-mod is applied to. Anything else is the
    owner's own editing and must keep blocking -- stashing and dropping
    that would be data loss.

    False on a clean tree: there is nothing to set aside.
    """
    files = dirty_tracked_files()
    if not files:
        return False
    expected = set(_AUTO_REGENERATED_FILES) | self_mod_owned_files()
    return all(f in expected for f in files)


def stash_expected_dirt(message: str) -> bool:
    """Stash exactly the files `only_expected_files_dirty` accepted.

    Named paths only, so untracked work in knowledge/ or workspace/ is
    never touched.
    """
    expected = set(_AUTO_REGENERATED_FILES) | self_mod_owned_files()
    paths_list = [f for f in dirty_tracked_files() if f in expected]
    if not paths_list:
        return False
    try:
        r = _git("stash", "push", "-m", message, "--", *paths_list, check=False)
        return r.returncode == 0
    except FileNotFoundError:
        return False


def drop_top_stash() -> None:
    """`git stash drop` the most recent stash. Best-effort — failure
    just leaves the stash entry for manual cleanup, not a data-loss
    issue."""
    try:
        _git("stash", "drop", check=False)
    except FileNotFoundError:
        pass


def restore_top_stash() -> None:
    """`git stash pop` the most recent stash. Used on update failure
    so the user's working tree returns to its pre-update state."""
    try:
        _git("stash", "pop", check=False)
    except FileNotFoundError:
        pass


def fetch_remote(branch: str) -> tuple[bool, str]:
    """`git fetch origin <branch>`. Returns (ok, error_msg)."""
    try:
        r = _git("fetch", "origin", branch, check=False)
        if r.returncode != 0:
            return False, (r.stderr or "git fetch failed").strip()
        return True, ""
    except FileNotFoundError:
        return False, "git not found on PATH"


def commits_ahead(branch: str = "master") -> list[dict]:
    """Commits on `origin/<branch>` that aren't in HEAD yet, formatted
    as `[{sha, subject}, ...]`. Newest last (git log default)."""
    try:
        r = _git(
            "log",
            f"HEAD..origin/{branch}",
            "--pretty=format:%h|%s",
            check=False,
        )
        if r.returncode != 0 or not r.stdout.strip():
            return []
        out = []
        for line in r.stdout.strip().splitlines():
            if "|" not in line:
                continue
            sha, _, subject = line.partition("|")
            out.append({"sha": sha.strip(), "subject": subject.strip()})
        return out
    except (FileNotFoundError, subprocess.CalledProcessError):
        return []


# --- history ledger -----------------------------------------------------


def load_history() -> list[HistoryEntry]:
    p = paths.history_path()
    if not p.exists():
        return []
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:
        log.warning("update_history.json unreadable (%s); starting fresh", e)
        return []
    entries = raw.get("entries") or []
    out: list[HistoryEntry] = []
    for e in entries:
        try:
            out.append(HistoryEntry(**e))
        except TypeError:
            continue
    return out


def save_history(entries: list[HistoryEntry]) -> None:
    p = paths.history_path()
    # Cap to most-recent MAX_HISTORY_ENTRIES so the ledger doesn't
    # grow forever. Keep newest, drop oldest.
    capped = entries[-MAX_HISTORY_ENTRIES:]
    payload = {"entries": [asdict(e) for e in capped]}
    # C3: atomic .tmp + rename. update_history.json is what
    # `hrant rollback` reads to find a known-good prior SHA — a
    # torn write at the wrong moment would force the user to dig
    # the SHA out of git reflog manually.
    paths.write_atomic_json(p, payload)


def record(sha: str, branch: str, result: str, note: str = "") -> HistoryEntry:
    """Append a history entry. Returns the entry written so the
    caller can show it."""
    entry = HistoryEntry(
        sha=sha,
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        branch=branch,
        result=result,
        note=note,
    )
    entries = load_history()
    entries.append(entry)
    save_history(entries)
    return entry


# --- pip / npm steps ----------------------------------------------------


def _run(cmd: list[str], cwd: Path) -> tuple[bool, str]:
    """Wrapper that runs a command and captures combined output for
    failure reporting. Used for pip / npm steps."""
    try:
        r = subprocess.run(
            cmd, cwd=str(cwd), capture_output=True, text=True, check=False,
        )
        if r.returncode != 0:
            return False, (r.stderr or r.stdout or "no output").strip()[-2000:]
        return True, (r.stdout or "").strip()[-1000:]
    except FileNotFoundError:
        return False, f"{cmd[0]} not found on PATH"


def run_pip_install() -> tuple[bool, str]:
    """`pip install -e .` from the engine repo root. Picks up any
    pyproject.toml dep changes the update brought in. Uses the
    same Python interpreter that the agent is running under."""
    import sys
    return _run(
        [sys.executable, "-m", "pip", "install", "-e", "."],
        cwd=paths.repo_root(),
    )


def run_frontend_build() -> tuple[bool, str]:
    """`npm install` + `npm run build` in frontend/. Both are
    captured into one combined result — failure at either step
    aborts and returns the stderr."""
    frontend = paths.repo_root() / "frontend"
    ok, out = _run(["npm", "install"], cwd=frontend)
    if not ok:
        return False, f"npm install: {out}"
    ok, out = _run(["npm", "run", "build"], cwd=frontend)
    if not ok:
        return False, f"npm run build: {out}"
    return True, "frontend rebuilt"


def frontend_changed(commits: list[dict]) -> bool:
    """Heuristic: did the incoming commits touch anything under
    frontend/? Used to skip the (slow) rebuild when only backend
    changed. Conservative — when in doubt, returns True.

    Examines each commit's file list via `git show --name-only`
    rather than diffing `HEAD..origin/<branch>`. The diff approach
    looks correct in isolation but `update()` calls this AFTER the
    pull has happened, at which point HEAD == origin/<branch> and
    the diff is empty — so the heuristic always reported "no
    frontend change" and skipped the rebuild. Walking commits
    directly works regardless of whether the pull has run yet.
    """
    if not commits:
        return False
    try:
        for c in commits:
            sha = (c.get("sha") or "").strip()
            if not sha:
                # Missing SHA from the caller — be conservative and
                # rebuild rather than silently skipping.
                return True
            r = _git(
                "show", "--name-only", "--pretty=format:", sha,
                check=False,
            )
            if r.returncode != 0:
                return True
            for line in r.stdout.splitlines():
                if line.strip().startswith("frontend/"):
                    return True
        return False
    except (FileNotFoundError, subprocess.CalledProcessError):
        return True


# --- top-level orchestration --------------------------------------------


def count_active_self_mods() -> int:
    """How many self-mods are currently active? Used by the
    pre-update prompt to decide whether to warn the user."""
    try:
        from . import self_mods
        return sum(
            1 for e in self_mods.list_patches()
            if e.status in ("applied", "needs_review")
        )
    except Exception:
        return 0


def do_update(
    *,
    branch: str = "master",
    skip_frontend: bool = False,
    skip_pip: bool = False,
    assume_yes: bool = False,
    confirm: Optional[callable] = None,  # type: ignore[type-arg]
) -> UpdateResult:
    """One-shot update. Returns UpdateResult; the CLI prints from it.

    When active self-mods exist and `assume_yes` is False, calls
    `confirm(prompt, default=False)` (provided by the CLI) to ask
    the user. Returns `cancelled=True` if the user said no.
    """
    messages: list[str] = []
    old = current_sha()
    br = current_branch() or branch
    # Snapshot version BEFORE the pull so we can show a before→after
    # delta on success. backend.version reads `git rev-list --count
    # HEAD` at call time, so re-resolving after the pull naturally
    # reports the new version with no extra bookkeeping.
    try:
        from . import version as _vmod
        _pre_version = _vmod.get_version()
    except Exception:
        _pre_version = ""

    # Pre-update consent. This used to say every active self-mod would be
    # archived, which stopped being true when the pull started sorting them
    # per patch -- and "they will all be deleted" is a good reason not to
    # update at all.
    active_count = count_active_self_mods()
    if active_count > 0 and not assume_yes:
        prompt = (
            f"You have {active_count} active self-modification(s). Each "
            "one is checked against the incoming code:" + chr(10)
            + "  still fits        - re-applied, stays active" + chr(10)
            + "  already upstream  - archived; the change is in the code "
              "now" + chr(10)
            + "  conflicts         - archived, and named in the output"
            + chr(10)
            + "Archived patches stay in ~/.hrant/data/self_mods/history/ "
              "and can be re-applied from Settings -> Self-Modifications "
              "-> History." + chr(10)
            + "Continue?"
        )
        proceed = confirm(prompt, default=False) if confirm is not None else False
        if not proceed:
            return UpdateResult(
                ok=False, old_sha=old, new_sha=None, branch=br,
                pulled_commits=0, pip_ran=False, frontend_built=False,
                error="cancelled by user (active self-mods would be archived)",
                cancelled=True,
            )

    # Auto-stash known-noisy files (lockfiles that the next step
    # regenerates anyway) so they don't keep blocking updates. Real
    # WIP edits still hold the line. Pre-fix, every fresh `npm
    # install` (run automatically by the previous update) left
    # `frontend/package-lock.json` modified — and the NEXT update
    # refused on it.
    stashed_noisy = False
    # Whether that stash holds an applied self-mod, which changes how
    # it may be disposed of: only a real pull re-applies patches, so
    # on the no-op path the stash is the only copy in the tree.
    stashed_self_mods = False
    if is_dirty():
        if only_expected_files_dirty():
            owned = self_mod_owned_files() & set(dirty_tracked_files())
            stashed_self_mods = bool(owned)
            if owned:
                # Not data loss: the patches are stored separately and
                # archive_all_active() re-applies the ones that still fit
                # once the pull has landed.
                messages.append(
                    f"setting aside {len(owned)} file(s) held by applied "
                    "self-mod(s); they are re-applied after the pull"
                )
            if set(dirty_tracked_files()) - owned:
                messages.append(
                    "auto-stashing noisy lockfile changes "
                    "(regenerated by npm install / pip install)"
                )
            stashed_noisy = stash_expected_dirt(
                "hrant-update: auto-stash lockfiles and applied self-mods"
            )
            if not stashed_noisy:
                return UpdateResult(
                    ok=False, old_sha=old, new_sha=None, branch=br,
                    pulled_commits=0, pip_ran=False, frontend_built=False,
                    error=(
                        "auto-stash of regenerated lockfiles failed; "
                        "stash them manually with `git stash` and retry."
                    ),
                )
        else:
            return UpdateResult(
                ok=False, old_sha=old, new_sha=None, branch=br,
                pulled_commits=0, pip_ran=False, frontend_built=False,
                error=(
                    "working tree has uncommitted tracked changes. "
                    "Commit or `git stash` them, then retry. "
                    "(Untracked files in knowledge/ or workspace/ don't count "
                    "and won't block the update.)"
                ),
            )

    def _release_stash_on_fail(res: UpdateResult) -> UpdateResult:
        """If we auto-stashed noisy lockfiles AND the update bailed,
        restore them so the working tree returns to its pre-update
        state. On SUCCESS we drop instead — the freshly regenerated
        lockfile is the canonical content."""
        if stashed_noisy:
            restore_top_stash()
        return res

    ok, err = fetch_remote(br)
    if not ok:
        return _release_stash_on_fail(UpdateResult(
            ok=False, old_sha=old, new_sha=None, branch=br,
            pulled_commits=0, pip_ran=False, frontend_built=False,
            error=f"git fetch failed: {err}",
        ))

    incoming = commits_ahead(br)
    if not incoming:
        # No-op update. A regenerated lockfile is noise and the stash is
        # dropped -- putting it back would just re-block the next update.
        # An applied self-mod is not noise: nothing re-applies it on this
        # path, because `archive_all_active()` runs only after a pull that
        # actually happened. Dropping it here removed two applied lessons
        # from prod on 2026-09-03.
        if stashed_noisy:
            if stashed_self_mods:
                restore_top_stash()
            else:
                drop_top_stash()
        msg = (
            f"already up to date (version {_pre_version})"
            if _pre_version else "already up to date"
        )
        return UpdateResult(
            ok=True, old_sha=old, new_sha=old, branch=br,
            pulled_commits=0, pip_ran=False, frontend_built=False,
            messages=[msg],
        )

    # Record BEFORE we change anything so a partial-fail update
    # still leaves a rollback point.
    record(old, br, "pre_update", note=f"about to pull {len(incoming)} commits")

    try:
        r = _git("pull", "--ff-only", "origin", br, check=False)
        if r.returncode != 0:
            record(old, br, "failed_at_pull", note=(r.stderr or "").strip()[:200])
            return _release_stash_on_fail(UpdateResult(
                ok=False, old_sha=old, new_sha=None, branch=br,
                pulled_commits=0, pip_ran=False, frontend_built=False,
                error=(
                    "git pull --ff-only refused (non-fast-forward; you have "
                    "local commits that aren't on origin). Resolve manually."
                ),
            ))
    except FileNotFoundError:
        return _release_stash_on_fail(UpdateResult(
            ok=False, old_sha=old, new_sha=None, branch=br,
            pulled_commits=0, pip_ran=False, frontend_built=False,
            error="git not found on PATH",
        ))

    new = current_sha()
    # Version snapshot AFTER the pull — backend.version reads
    # `git rev-list --count HEAD` at call time, so this reflects
    # the post-pull state. `_pre_version` is captured at the top of
    # this function for the before-side of the delta.
    from . import version as _vmod
    post_version = _vmod.get_version()
    if _pre_version and post_version and _pre_version != post_version:
        messages.append(
            f"pulled {len(incoming)} commits ({old[:8]} → {new[:8]}, "
            f"version {_pre_version} → {post_version})"
        )
    else:
        messages.append(
            f"pulled {len(incoming)} commits ({old[:8]} → {new[:8]})"
        )

    pip_ran = False
    if not skip_pip:
        ok, out = run_pip_install()
        pip_ran = ok
        if not ok:
            record(new, br, "failed_at_pip", note=out[:200])
            return _release_stash_on_fail(UpdateResult(
                ok=False, old_sha=old, new_sha=new, branch=br,
                pulled_commits=len(incoming), pip_ran=False, frontend_built=False,
                error=f"pip install -e . failed: {out[:500]}",
            ))
        messages.append("pip install -e . ✓")

    fe_built = False
    if not skip_frontend:
        if not frontend_changed(incoming):
            messages.append("frontend unchanged — skipped npm build")
        else:
            ok, out = run_frontend_build()
            fe_built = ok
            if not ok:
                record(new, br, "failed_at_frontend", note=out[:200])
                return _release_stash_on_fail(UpdateResult(
                    ok=False, old_sha=old, new_sha=new, branch=br,
                    pulled_commits=len(incoming), pip_ran=pip_ran,
                    frontend_built=False,
                    error=f"frontend build failed: {out[:500]}",
                ))
            messages.append("frontend rebuilt ✓")

    # Archive any active self-modifications. The engine is now at
    # origin/master; user re-applies what they want from the WebUI's
    # History panel. This trades automation for predictability — a
    # user-facing update is loud and never silently breaks the engine.
    archived_count = 0
    archive_id: Optional[str] = None
    try:
        from . import self_mods
        archive_report = self_mods.archive_all_active()
        archived_count = archive_report.get("archived_count", 0) or 0
        archive_id = archive_report.get("archive_id")
        _kept = archive_report.get("kept") or []
        _conflicted = archive_report.get("conflicted") or []
        if _kept:
            # The point of the change: a fix the agent made, which is not
            # in git yet, is carried across the deploy instead of being
            # thrown away and quietly re-broken.
            messages.append(
                f"kept {len(_kept)} self-mod(s) not yet upstream: "
                f"{', '.join(_kept)}"
            )
        if archived_count > 0:
            messages.append(
                f"archived {archived_count} self-mod(s) → "
                f"~/.hrant/data/self_mods/history/{archive_id}/"
            )
        if _conflicted:
            # Loud, because this is the one case where work is lost: the
            # pull moved the same code and no honest merge is available.
            messages.append(
                f"WARNING: {len(_conflicted)} self-mod(s) conflicted with "
                f"the update and were archived unapplied: "
                f"{', '.join(_conflicted)} — re-propose or re-apply by hand"
            )
    except Exception as e:  # pragma: no cover — defensive
        messages.append(f"self_mods archive skipped due to error: {e}")

    # Drop the auto-stash on success — the freshly regenerated
    # lockfile is now the canonical content. Restoring the stashed
    # OLD lockfile would only re-introduce the noise that triggered
    # this whole code path.
    if stashed_noisy:
        drop_top_stash()

    record(new, br, "success", note=f"updated from {old[:8]}")
    return UpdateResult(
        ok=True, old_sha=old, new_sha=new, branch=br,
        pulled_commits=len(incoming), pip_ran=pip_ran,
        frontend_built=fe_built, messages=messages,
        self_mods_archived=archived_count,
        self_mods_archive_id=archive_id,
    )


def do_rollback(
    *,
    to_sha: Optional[str] = None,
    skip_frontend: bool = False,
    skip_pip: bool = False,
) -> UpdateResult:
    """Reset HEAD to a previous SHA from history (or `to_sha`).

    Strategy:
      - If `to_sha` is None: use the entry BEFORE the most recent
        successful one (i.e. one step back).
      - Refuse on dirty tree (same reasoning as update).
      - `git reset --hard` is destructive — but since the user
        invoked rollback knowing what it does, we trust the call.
      - Same pip + frontend rebuild steps as update so the engine's
        deps match the rolled-back code.
    """
    messages: list[str] = []
    if is_dirty():
        return UpdateResult(
            ok=False, old_sha=current_sha(), new_sha=None,
            branch=current_branch() or "master",
            pulled_commits=0, pip_ran=False, frontend_built=False,
            error="working tree dirty; commit or stash first",
        )

    old = current_sha()
    br = current_branch() or "master"

    if to_sha is None:
        entries = load_history()
        # Walk back to find a successful entry OLDER than the current
        # SHA. Default behaviour: roll back one step.
        successes = [e for e in entries if e.result == "success"]
        if len(successes) < 1:
            return UpdateResult(
                ok=False, old_sha=old, new_sha=None, branch=br,
                pulled_commits=0, pip_ran=False, frontend_built=False,
                error=(
                    "no rollback target — history is empty or has no "
                    "successful update entries. Pass --to <sha> to choose "
                    "a target explicitly."
                ),
            )
        # The most recent success is the CURRENT state. Want the one
        # before that.
        if len(successes) < 2:
            # Try the pre_update entry (recorded just before the most
            # recent update) — that's a valid "go back to before the
            # last update" target.
            pre = [e for e in entries if e.result == "pre_update"]
            if not pre:
                return UpdateResult(
                    ok=False, old_sha=old, new_sha=None, branch=br,
                    pulled_commits=0, pip_ran=False, frontend_built=False,
                    error="no previous version in history to roll back to",
                )
            to_sha = pre[-1].sha
        else:
            to_sha = successes[-2].sha

    try:
        r = _git("reset", "--hard", to_sha, check=False)
        if r.returncode != 0:
            return UpdateResult(
                ok=False, old_sha=old, new_sha=None, branch=br,
                pulled_commits=0, pip_ran=False, frontend_built=False,
                error=f"git reset --hard {to_sha} failed: {r.stderr.strip()[:300]}",
            )
    except FileNotFoundError:
        return UpdateResult(
            ok=False, old_sha=old, new_sha=None, branch=br,
            pulled_commits=0, pip_ran=False, frontend_built=False,
            error="git not found on PATH",
        )

    new = current_sha()
    messages.append(f"reset to {new[:8]} (was {old[:8]})")

    pip_ran = False
    if not skip_pip:
        ok, out = run_pip_install()
        pip_ran = ok
        if not ok:
            record(new, br, "rollback_partial", note=f"pip failed: {out[:200]}")
            return UpdateResult(
                ok=False, old_sha=old, new_sha=new, branch=br,
                pulled_commits=0, pip_ran=False, frontend_built=False,
                error=f"reset OK but pip install -e . failed: {out[:500]}",
            )
        messages.append("pip install -e . ✓")

    fe_built = False
    if not skip_frontend:
        ok, out = run_frontend_build()
        fe_built = ok
        if not ok:
            record(new, br, "rollback_partial", note=f"frontend failed: {out[:200]}")
            return UpdateResult(
                ok=False, old_sha=old, new_sha=new, branch=br,
                pulled_commits=0, pip_ran=pip_ran, frontend_built=False,
                error=f"reset + pip OK but frontend build failed: {out[:500]}",
            )
        messages.append("frontend rebuilt ✓")

    record(new, br, "rollback", note=f"rolled back from {old[:8]}")
    return UpdateResult(
        ok=True, old_sha=old, new_sha=new, branch=br,
        pulled_commits=0, pip_ran=pip_ran, frontend_built=fe_built,
        messages=messages,
    )
