"""FIRE_GOAL_EXECUTOR — drive improvement-goals through their
subtasks programmatically.

Audit 2026-05-27 prod state: 18 active goals, all generated by
meta_learner, all stuck. Subtasks of the form
  - "Run SELF_MODIFIER.analyze_module('verifier')"
  - "Review the resulting proposal in the WebUI"
  - "Approve or reject explicitly"

The first two CAN be done by the autonomic loop. The third stays
human. The lever executes (1) and (2), marks them done, leaves
(3) for the operator. After STALE_DAYS waiting on (3), archives
the goal as `failed` with a clear reason.
"""
from __future__ import annotations

from datetime import datetime, timedelta


def _make_improvement_goal(*, age_days: int = 0, target_module: str = "verifier"):
    """Build a goal in the shape meta_learner produces."""
    from backend.goals import Goal
    created = (datetime.now() - timedelta(days=age_days)).strftime(
        "%Y-%m-%d %H:%M:%S"
    )
    g = Goal(
        description=f"Improve prompt: target {target_module}",
        priority=6,
        goal_type="improvement",
        source="meta_learner_pattern",
        created=created,
        context=f"Target module guess: {target_module}",
    )
    g.add_subtask(f"Run SELF_MODIFIER.analyze_module('{target_module}')")
    g.add_subtask("Review the resulting proposal in the WebUI")
    g.add_subtask("Approve or reject explicitly")
    return g


def test_lever_registered():
    from backend.autonomic.levers import (
        register_default_autonomic_levers, clear_registry, list_levers,
    )
    clear_registry()
    try:
        register_default_autonomic_levers()
        assert "FIRE_GOAL_EXECUTOR" in list_levers()
    finally:
        clear_registry()


def test_skip_when_no_active_improvement_goals(monkeypatch):
    """No active improvement-goals → skip."""
    from backend.autonomic.levers.goal_executor import FIRE_GOAL_EXECUTOR
    from backend.autonomic.types import LeverStatus
    from backend import goals as g_mod

    monkeypatch.setattr(g_mod.GOALS, "_goals", [])
    lever = FIRE_GOAL_EXECUTOR()
    report = lever.run({}, {})
    assert report.status == LeverStatus.SKIPPED


def test_executes_analyze_module_subtask(monkeypatch):
    """The first subtask matches the analyze_module pattern.
    Lever extracts the module name and calls SELF_MODIFIER, then
    marks the subtask done."""
    from backend.autonomic.levers.goal_executor import FIRE_GOAL_EXECUTOR
    from backend.autonomic.types import LeverStatus
    from backend import goals as g_mod
    from backend import self_modifier as sm

    goal = _make_improvement_goal(target_module="verifier")
    monkeypatch.setattr(g_mod.GOALS, "_goals", [goal])
    monkeypatch.setattr(g_mod.GOALS, "_save", lambda: None)

    captured: dict = {}

    def _stub_analyze(module_name):
        captured["module"] = module_name
        # Return a fake proposal list
        return [sm.Proposal(id="p_new", module=f"backend/{module_name}.py",
                            title="x", description="x", status="pending")]
    monkeypatch.setattr(sm.SELF_MODIFIER, "analyze_module", _stub_analyze)

    lever = FIRE_GOAL_EXECUTOR()
    report = lever.run({}, {})

    assert report.status == LeverStatus.SUCCESS
    assert captured["module"] == "verifier"
    # Subtask 0 (Run analyze_module) marked done.
    assert goal.subtasks[0]["status"] == "done"
    # Result note references the new proposal id.
    assert "p_new" in goal.subtasks[0]["result"]


def test_review_subtask_marked_done_when_proposals_exist(monkeypatch):
    """Once SELF_MODIFIER has proposals for the target module, the
    'Review in WebUI' subtask is marked done automatically — the
    review surface is the WebUI, not the lever's responsibility."""
    from backend.autonomic.levers.goal_executor import FIRE_GOAL_EXECUTOR
    from backend import goals as g_mod
    from backend import self_modifier as sm

    goal = _make_improvement_goal(target_module="verifier")
    # Pretend analyze_module already ran (subtask 0 done).
    goal.complete_subtask(0, "Already analyzed earlier — proposal=p_old")
    monkeypatch.setattr(g_mod.GOALS, "_goals", [goal])
    monkeypatch.setattr(g_mod.GOALS, "_save", lambda: None)

    # SELF_MODIFIER has a proposal targeting verifier.
    monkeypatch.setattr(
        sm.SELF_MODIFIER, "_proposals",
        [sm.Proposal(id="p_old", module="backend/verifier.py",
                     title="x", description="x", status="pending")],
    )
    monkeypatch.setattr(sm.SELF_MODIFIER, "analyze_module",
                        lambda mn: [])

    lever = FIRE_GOAL_EXECUTOR()
    report = lever.run({}, {})

    assert goal.subtasks[1]["status"] == "done"
    # The third subtask stays pending (human-only).
    assert goal.subtasks[2]["status"] == "pending"


def test_does_not_auto_complete_approval_subtask(monkeypatch):
    """The 'Approve or reject explicitly' subtask is reserved for
    the human. Even with the other two done, the lever does NOT
    flip it. The goal stays active waiting for review."""
    from backend.autonomic.levers.goal_executor import FIRE_GOAL_EXECUTOR
    from backend import goals as g_mod
    from backend import self_modifier as sm

    goal = _make_improvement_goal()
    goal.complete_subtask(0, "p_x")
    goal.complete_subtask(1, "reviewed")
    monkeypatch.setattr(g_mod.GOALS, "_goals", [goal])
    monkeypatch.setattr(g_mod.GOALS, "_save", lambda: None)
    monkeypatch.setattr(sm.SELF_MODIFIER, "_proposals", [])
    monkeypatch.setattr(sm.SELF_MODIFIER, "analyze_module",
                        lambda mn: [])

    lever = FIRE_GOAL_EXECUTOR()
    lever.run({}, {})

    assert goal.subtasks[2]["status"] == "pending"
    assert goal.status == "active"


def test_archives_old_goals_stuck_on_approval(monkeypatch):
    """A goal whose only-remaining subtask is the human approval
    step AND has been waiting longer than STALE_DAYS gets marked
    `failed` with a clear reason — clears the backlog."""
    from backend.autonomic.levers.goal_executor import (
        FIRE_GOAL_EXECUTOR, STALE_DAYS,
    )
    from backend import goals as g_mod
    from backend import self_modifier as sm

    old_goal = _make_improvement_goal(age_days=STALE_DAYS + 5)
    old_goal.complete_subtask(0, "x")
    old_goal.complete_subtask(1, "x")
    # Only "Approve or reject explicitly" remains pending — but
    # 19 days have passed.
    monkeypatch.setattr(g_mod.GOALS, "_goals", [old_goal])
    monkeypatch.setattr(g_mod.GOALS, "_save", lambda: None)
    monkeypatch.setattr(sm.SELF_MODIFIER, "_proposals", [])
    monkeypatch.setattr(sm.SELF_MODIFIER, "analyze_module",
                        lambda mn: [])

    lever = FIRE_GOAL_EXECUTOR()
    lever.run({}, {})

    assert old_goal.status == "failed"
    assert "stale" in (old_goal.progress_notes[-1] if old_goal.progress_notes
                       else "").lower() or old_goal.completed is not None


def test_handles_unparseable_subtask_descriptions(monkeypatch):
    """A goal with subtask descriptions that don't match the known
    patterns (free-form text from user-added goals) is skipped
    cleanly — no exception, no spurious action."""
    from backend.autonomic.levers.goal_executor import FIRE_GOAL_EXECUTOR
    from backend import goals as g_mod
    from backend.goals import Goal

    custom_goal = Goal(
        description="user typed something else",
        goal_type="improvement",
        subtasks=[
            {"description": "do thing X", "status": "pending", "result": ""},
        ],
    )
    monkeypatch.setattr(g_mod.GOALS, "_goals", [custom_goal])
    monkeypatch.setattr(g_mod.GOALS, "_save", lambda: None)

    lever = FIRE_GOAL_EXECUTOR()
    report = lever.run({}, {})
    # Status doesn't matter — the goal just isn't touched.
    assert custom_goal.subtasks[0]["status"] == "pending"
